# Задача 1

In [1]:
import numpy as np
import scipy.stats as sps
import matplotlib.pyplot as plt

In [10]:
def random_matrix(n, m, lower=0, upper=1):
    return sps.uniform.rvs(size=(n, m), loc=lower, scale=(upper - lower))

random_matrix(2, 3, -5, 5)

array([[-0.34141064, -0.53500503,  3.56123804],
       [-1.09327666,  1.48513268,  2.50466517]])

In [12]:
def random_diagonal(n, lower=0, upper=1):
    return np.diag(sps.uniform.rvs(size=n, loc=lower, scale=(upper - lower)))

random_diagonal(5)

array([[0.20283488, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.12560051, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.58625959, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.43550511, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.23654224]])

In [20]:
def random_upper_triangle(n, lower=0, upper=1):
    return np.triu(random_matrix(n, n, lower=lower, upper=upper))
                   
random_upper_triangle(5, -3, 3)

array([[ 1.92754008, -2.328208  ,  0.49039532, -0.89846331,  1.4442346 ],
       [ 0.        , -0.71697344,  2.08436856, -2.0779628 ,  1.56399259],
       [ 0.        ,  0.        , -1.19945791,  1.66144564,  2.55610355],
       [ 0.        ,  0.        ,  0.        ,  0.0032087 , -1.80349418],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.80059967]])

In [23]:
def random_lower_triangle(n, lower=0, upper=1):
    return random_upper_triangle(n, lower=lower, upper=upper).T

random_lower_triangle(5, -2, 2)

array([[-0.96609331,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.47445188,  0.6311682 ,  0.        ,  0.        ,  0.        ],
       [ 0.91149784,  1.00480846,  0.36805823,  0.        ,  0.        ],
       [-1.33329789,  0.68800842, -1.98864867, -1.64330495,  0.        ],
       [ 1.93505898, -0.43456789,  1.1528668 , -1.47860847,  1.08464121]])

In [24]:
def random_symmetrical(n, lower=0, upper=1):
    x = random_matrix(n, n, lower=lower, upper=upper)
    return((x + x.T) / 2)

random_symmetrical(5)

array([[0.42126152, 0.46234986, 0.31957721, 0.85463852, 0.55231658],
       [0.46234986, 0.37097196, 0.54902731, 0.5714095 , 0.68430021],
       [0.31957721, 0.54902731, 0.90359489, 0.6266679 , 0.86019018],
       [0.85463852, 0.5714095 , 0.6266679 , 0.08681551, 0.21088824],
       [0.55231658, 0.68430021, 0.86019018, 0.21088824, 0.03104485]])

# Задачи 2, 3, 4

[Решение](hw_1_3_1.pdf)