In [6]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sps


# Задание 1

In [2]:
def hilbert(n):
  x = np.arange(1, n+1) + np.arange(0, n)[:, np.newaxis]
  return 1/x

print(hilbert(3))

[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]


In [4]:
u, s, v = np.linalg.svd(hilbert(5))
print(u, s, v, sep='\n')

[[-0.76785474  0.60187148 -0.21421362  0.04716181  0.00617386]
 [-0.44579106 -0.27591342  0.72410213 -0.43266733 -0.11669275]
 [-0.32157829 -0.42487662  0.12045328  0.66735044  0.50616366]
 [-0.25343894 -0.44390304 -0.30957397  0.23302452 -0.76719119]
 [-0.20982264 -0.42901335 -0.56519341 -0.55759995  0.37624555]]
[1.56705069e+00 2.08534219e-01 1.14074916e-02 3.05898040e-04
 3.28792877e-06]
[[-0.76785474 -0.44579106 -0.32157829 -0.25343894 -0.20982264]
 [ 0.60187148 -0.27591342 -0.42487662 -0.44390304 -0.42901335]
 [-0.21421362  0.72410213  0.12045328 -0.30957397 -0.56519341]
 [ 0.04716181 -0.43266733  0.66735044  0.23302452 -0.55759995]
 [ 0.00617386 -0.11669275  0.50616366 -0.76719119  0.37624555]]


# Задание 2

In [47]:
def random_from_cov(cov):
  n = cov.shape[0]
  a = np.linalg.cholesky(cov)
  # print(a)
  z = sps.norm.rvs(size=n)
  # print(z)
  return a @ z


In [64]:
# проверка 

cov = np.array([[1, 0.2, 0.7], [0.2, 1, 0.2], [0.7, 0.2, 1]])
print(random_from_cov(cov))

vals = random_from_cov(cov)
for i in range(999):
  vals = np.vstack((vals, random_from_cov(cov)))

np.cov(vals.T)

[ 0.20988836  1.19598562 -0.26745531]


array([[1.01654794, 0.16469328, 0.72466442],
       [0.16469328, 0.96147203, 0.16572841],
       [0.72466442, 0.16572841, 1.02602784]])

Видим, что полученная матрица ковариции близка к изначальной, а значит метод работает.